import Image from "next/image";
import Link from "next/link";
import { Bot, CheckCircle2, ExternalLink, MessageSquare, Palette, Search, ShieldCheck, Sparkles } from "lucide-react";

import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { ProductVisualGallery } from "@/components/product-visual-gallery";
import { canonicalUrl } from "@/config/metadata";
import { hyperAppsUpdatedAt } from "@/data/hyper-apps";
import { getHyperAppEs as getHyperApp } from "@/data/hyper-apps.es";
import { createSpanishPageMetadata } from "@/lib/i18n/metadata";
import { toJsonLd } from "@/lib/schema";

const app = getHyperApp("chat");
const title = "Chat con IA y preguntas frecuentes para Shopify | Hyper AI Chat";
const description = "Responde preguntas de clientes sobre productos, envios, devoluciones y politicas con un chatbot de IA y preguntas frecuentes para Shopify.";
const pagePath = "/es/apps/hyper-ai-chat-faq";
const pageUrl = canonicalUrl(pagePath);

export const metadata = createSpanishPageMetadata({ title, description, path: pagePath });

const features = [[Bot, "Chatbot de IA para Shopify", "Responde preguntas comunes de clientes con contenido aprobado de la tienda."], [Search, "preguntas frecuentes buscables", "Publica respuestas claras para productos, envios, devoluciones, tallas y politicas."], [MessageSquare, "Historial de conversaciones", "Revisa temas repetidos para encontrar brechas de contenido y soporte."], [Palette, "Personalizacion de widget", "Ajusta el aspecto del chat y la experiencia de preguntas frecuentes para la marca."], [ShieldCheck, "Contenido controlado", "Entrena respuestas con productos, preguntas frecuentes, politicas y soporte que tu equipo aprueba."], [Sparkles, "Analitica de soporte", "Observa uso, preguntas frecuentes y actividad para mejorar el autoservicio."]] as const;
const problems = ["Preguntas repetidas sobre productos", "Dudas de tallas, envio o devoluciones", "Clientes esperando respuesta antes de comprar", "Contenido de politicas dificil de encontrar", "Equipos de soporte con conversaciones repetitivas", "Brechas en preguntas frecuentes y documentacion"];
const productVisuals = [
  { src: "/aichat-banner.png", alt: "Experiencia de chat IA y preguntas frecuentes de Hyper AI Chat", title: "Chat IA y preguntas frecuentes", body: "Ofrece a compradores un lugar claro para preguntar sobre productos, envios, devoluciones y politicas usando contenido aprobado." },
  { src: "/aichat-benefit-1.png", alt: "Flujo de respuestas de Hyper AI Chat para preguntas de producto", title: "Respuestas sobre productos", body: "Apoya preguntas previas a compra cuando la informacion relevante existe en el contenido conectado de la tienda." },
  { src: "/aichat-benefit-2.png", alt: "Pantalla de gestion de preguntas frecuentes de Hyper AI Chat", title: "Contenido de autoservicio", body: "Organiza respuestas aprobadas para que compradores puedan navegar y buscar ayuda sin abrir un ticket." },
  { src: "/aichat-benefit-3.png", alt: "Interfaz de historial y analitica de Hyper AI Chat", title: "Historial y analitica", body: "Revisa preguntas de compradores e identifica respuestas faltantes sin prometer automatizacion no verificada." },
  { src: "/aichat-benefit-4.png", alt: "Configuracion visual del widget de Hyper AI Chat", title: "Personalizacion del widget", body: "Ajusta la experiencia visual para que el chat se sienta coherente con la marca de la tienda." },
  { src: "/aichat-benefit-5.png", alt: "Vista adicional de experiencia de soporte de Hyper AI Chat", title: "Experiencia de soporte", body: "Mantiene respuestas y soporte de compra en un flujo accesible para compradores Shopify." },
];
const faq = [["Que hace Hyper AI Chat & FAQs?", "Ayuda a tiendas Shopify a responder preguntas comunes con chat IA y contenido de preguntas frecuentes buscables."], ["Puede usar informacion de mi tienda?", "Si. La app puede entrenarse con productos, preguntas frecuentes, politicas y contenido de soporte aprobado."], ["Hay plan gratis?", "Si. La informacion de planes muestra un plan gratis con limite mensual de conversaciones de IA."], ["Necesita codigo?", "La configuracion normal se realiza desde Shopify y la app; temas personalizados pueden requerir revision."]] as const;
const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", "@id": `${pageUrl}#webpage`, name: title, description, url: pageUrl, inLanguage: "es", isPartOf: { "@id": `${canonicalUrl("/")}#website` } }, { "@type": "SoftwareApplication", "@id": `${pageUrl}#software`, name: app.officialName, applicationCategory: "Shopify application", operatingSystem: "Shopify", url: pageUrl, sameAs: app.installHref, installUrl: app.installHref, image: canonicalUrl(app.screenshot), description, offers: app.plans.map((plan) => ({ "@type": "Offer", name: plan.name, price: plan.price === "$0" ? "0" : plan.price.replace(/[^0-9.]/g, ""), priceCurrency: "USD", url: app.installHref })) }, { "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] };

export default function SpanishAiChatPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: toJsonLd(schema) }} />
      <Section className="border-b border-border bg-[linear-gradient(180deg,hsl(var(--surface)),hsl(var(--background)))] pb-14 pt-16 sm:pt-20 lg:pt-24"><Container><div><div className="inline-flex items-center gap-3 rounded-[8px] border border-border bg-background px-4 py-2 shadow-sm"><Image src={app.icon} alt="" width={28} height={28} aria-hidden="true" className="rounded-[6px]" /><span className="text-sm font-bold text-muted-foreground">Hyper AI Chat & FAQs para Shopify</span></div><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[1.08] tracking-normal text-foreground sm:text-5xl lg:text-6xl">Chat con IA y preguntas frecuentes para responder preguntas de compradores Shopify</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Ayuda a compradores a obtener respuestas sobre productos, tallas, envios, devoluciones, disponibilidad y politicas de tienda sin esperar a soporte.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><Link href={app.installHref} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[6px] bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90">Instalar en Shopify <ExternalLink aria-hidden="true" className="size-4" /></Link><Link href={app.demoHref} className="inline-flex min-h-11 items-center justify-center rounded-[6px] border border-border bg-background px-6 py-3 text-sm font-bold text-foreground transition hover:border-primary/60">Ver tienda demo</Link><Link href="#pricing" className="inline-flex min-h-11 items-center justify-center px-2 text-sm font-bold text-primary underline-offset-4 hover:underline">Comparar planes</Link></div></div></Container></Section>
      <ProductVisualGallery eyebrow="Visuales del producto" title="Ver la experiencia de chat y preguntas frecuentes" body="Revisa el asistente de chat en tienda, superficies de preguntas frecuentes e historial que ayudan a detectar preguntas repetidas sobre productos, envios, devoluciones y politicas." visuals={productVisuals} />

      <Section spacing="lg"><Container className="grid gap-8 lg:grid-cols-[0.78fr_1.22fr]"><div><h2 className="text-3xl font-black tracking-normal">Cuando las preguntas quedan sin respuesta, la compra se enfria.</h2><p className="mt-4 text-muted-foreground">El chat con IA y las preguntas frecuentes ayudan a responder dudas repetidas antes de que bloqueen una decision de compra.</p></div><div className="grid gap-3 sm:grid-cols-2">{problems.map((problem) => (<div key={problem} className="rounded-[8px] border border-border bg-surface p-4 text-sm text-muted-foreground">{problem}</div>))}</div></Container></Section>
      <Section spacing="lg" className="bg-surface"><Container><div className="max-w-3xl"><h2 className="text-3xl font-black tracking-normal">Funciones principales</h2><p className="mt-4 text-muted-foreground">Capacidades pensadas para responder dudas de compra y mejorar autoservicio.</p></div><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, featureTitle, body]) => (<article key={featureTitle} className="rounded-[8px] border border-border bg-background p-6"><Icon aria-hidden="true" className="size-6 text-primary" /><h3 className="mt-4 text-xl font-black tracking-normal">{featureTitle}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p></article>))}</div></Container></Section>
      <Section id="pricing" spacing="lg"><Container><div className="max-w-3xl"><h2 className="text-3xl font-black tracking-normal">Planes segun volumen de conversaciones</h2><p className="mt-4 text-muted-foreground">Planes verificados contra Shopify App Store el {hyperAppsUpdatedAt}. Shopify es la fuente final de facturacion.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-4">{app.plans.map((plan) => (<article key={plan.name} className="flex min-h-[30rem] flex-col rounded-[8px] border border-border bg-surface p-5"><h3 className="text-xl font-black tracking-normal">{plan.name}</h3><p className="mt-3 text-3xl font-black tracking-normal">{plan.price}</p>{plan.trial ? <p className="mt-3 text-sm font-semibold text-primary">{plan.trial}</p> : null}<p className="mt-4 text-sm leading-6 text-muted-foreground">{plan.description}</p><ul className="mt-5 space-y-2">{plan.limits.slice(0, 5).map((item) => (<li key={item} className="flex gap-2 text-sm leading-5 text-muted-foreground"><CheckCircle2 aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary" /><span>{item}</span></li>))}</ul><Link href={app.installHref} className="mt-auto inline-flex min-h-11 items-center justify-center gap-2 rounded-[6px] bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90">{plan.cta ?? "Instalar"}</Link></article>))}</div></Container></Section>
      <Section spacing="lg" className="bg-surface"><Container size="md"><header className="text-center"><h2 className="text-3xl font-black tracking-normal">Preguntas frecuentes</h2></header><div className="mt-8 divide-y divide-border rounded-[8px] border border-border bg-background">{faq.map(([question, answer]) => (<details key={question} className="group p-5"><summary className="cursor-pointer list-none text-base font-black text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&::-webkit-details-marker]:hidden"><span className="flex items-center justify-between gap-4">{question}<span aria-hidden="true" className="text-primary">+</span></span></summary><p className="mt-4 text-sm leading-7 text-muted-foreground">{answer}</p></details>))}</div></Container></Section>
    </>
  );
}
