import Image from "next/image";
import Link from "next/link";
import { BarChart3, CheckCircle2, ExternalLink, Film, PlaySquare, ShoppingBag, Sparkles, Tags, Video } from "lucide-react";

import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { ProductVisualGallery } from "@/components/product-visual-gallery";
import { canonicalUrl } from "@/config/metadata";
import { hyperAppsUpdatedAt } from "@/data/hyper-apps";
import { getHyperAppEs as getHyperApp } from "@/data/hyper-apps.es";
import { createSpanishPageMetadata } from "@/lib/i18n/metadata";
import { toJsonLd } from "@/lib/schema";

const app = getHyperApp("video");
const title = "Videos comprables para Shopify | Hyper Shoppable Videos";
const description = "Convierte videos de producto, UGC y contenido social en componentes comprables para Shopify con productos etiquetados.";
const pagePath = "/es/apps/hyper-shoppable-videos";
const pageUrl = canonicalUrl(pagePath);

export const metadata = createSpanishPageMetadata({ title, description, path: pagePath });

const features = [[Tags, "Productos etiquetados", "Etiqueta productos dentro de videos para que compradores exploren lo que estan viendo."], [ShoppingBag, "Acciones de compra", "Acerca a los compradores a productos y carrito desde la experiencia de video."], [PlaySquare, "Widgets de tienda", "Usa carruseles, historias moviles y embeds en paginas de tienda."], [Film, "Importacion y subida", "Sube videos manualmente o usa importaciones sociales segun el plan."], [BarChart3, "Analitica de video", "Revisa vistas, clics, interacciones y senales de compra."], [Video, "Contenido social y UGC", "Convierte demos, tutoriales, Reels, TikToks y UGC en contenido comprable."]] as const;
const problems = ["Videos con vistas pero sin clics de producto", "UGC dificil de convertir en compra", "Demos que no conectan con producto", "Contenido social separado de la tienda", "Poca visibilidad de interaccion de video", "Compradores sin siguiente paso claro"];
const productVisuals = [
  { src: "/shoppable-banner.png", alt: "Widget de video comprable de Hyper Shoppable Videos con producto etiquetado", title: "Widget de video comprable", body: "Muestra videos de producto con elementos etiquetados y acciones de compra manteniendo clara la experiencia de pagina." },
  { src: "/shopable-benefit-1.png", alt: "Flujo de etiquetado de productos y gestion de videos de Hyper Shoppable Videos", title: "Flujo de videos etiquetados", body: "Conecta productos Shopify con los articulos que aparecen en el contenido de video." },
  { src: "/shopable-benefit-2.png", alt: "Pantalla de gestion de componentes de video de Hyper Shoppable Videos", title: "Componentes y ubicaciones", body: "Organiza componentes de video comprable para paginas de inicio, producto, coleccion y landing donde el tema lo permita." },
  { src: "/shopable-benefit-3.png", alt: "Vista de analitica de Hyper Shoppable Videos para vistas clics y eventos de carrito", title: "Analitica de interaccion", body: "Revisa vistas, clics de producto y eventos de carrito sin presentar esas acciones como compras completadas." },
];
const faq = [["Que hace Hyper Shoppable Videos?", "Convierte videos en experiencias comprables con productos etiquetados y componentes para Shopify."], ["Sirve para TikTok, Reels o UGC?", "Si. Es ideal para demos, tutoriales, contenido social y UGC segun las opciones de carga/importacion del plan."], ["Hay plan gratis?", "Si. La informacion de planes muestra un plan gratis con limites de videos, componentes y vistas."], ["Necesita codigo?", "La configuracion normal se realiza desde Shopify y la app; la colocacion exacta puede depender del tema."]] as const;
const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", "@id": `${pageUrl}#webpage`, name: title, description, url: pageUrl, inLanguage: "es", isPartOf: { "@id": `${canonicalUrl("/")}#website` } }, { "@type": "SoftwareApplication", "@id": `${pageUrl}#software`, name: app.officialName, applicationCategory: "Shopify application", operatingSystem: "Shopify", url: pageUrl, sameAs: app.installHref, installUrl: app.installHref, image: canonicalUrl(app.screenshot), description, offers: app.plans.map((plan) => ({ "@type": "Offer", name: plan.name, price: plan.price === "$0" ? "0" : plan.price.replace(/[^0-9.]/g, ""), priceCurrency: "USD", url: app.installHref })) }, { "@type": "FAQPage", "@id": `${pageUrl}#faq`, mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] };

export default function SpanishShoppableVideosPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: toJsonLd(schema) }} />
      <Section className="border-b border-border bg-[linear-gradient(180deg,hsl(var(--surface)),hsl(var(--background)))] pb-14 pt-16 sm:pt-20 lg:pt-24"><Container><div><div className="inline-flex items-center gap-3 rounded-[8px] border border-border bg-background px-4 py-2 shadow-sm"><Image src={app.icon} alt="" width={28} height={28} aria-hidden="true" className="rounded-[6px]" /><span className="text-sm font-bold text-muted-foreground">Hyper Shoppable Videos para Shopify</span></div><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[1.08] tracking-normal text-foreground sm:text-5xl lg:text-6xl">Videos comprables para tiendas Shopify</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Convierte videos de producto, contenido social y UGC en experiencias comprables con productos etiquetados, componentes de tienda y analitica.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><Link href={app.installHref} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[6px] bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90">Instalar en Shopify <ExternalLink aria-hidden="true" className="size-4" /></Link><Link href={app.demoHref} className="inline-flex min-h-11 items-center justify-center rounded-[6px] border border-border bg-background px-6 py-3 text-sm font-bold text-foreground transition hover:border-primary/60">Ver tienda demo</Link><Link href="#pricing" className="inline-flex min-h-11 items-center justify-center px-2 text-sm font-bold text-primary underline-offset-4 hover:underline">Comparar planes</Link></div></div></Container></Section>
      <ProductVisualGallery eyebrow="Visuales del producto" title="Ver la experiencia de video comprable" body="Revisa como los comerciantes conectan productos a videos, publican carruseles y componentes de video, y revisan vistas, clics de producto y actividad de carrito." visuals={productVisuals} />

      <Section spacing="lg"><Container className="grid gap-8 lg:grid-cols-[0.78fr_1.22fr]"><div><h2 className="text-3xl font-black tracking-normal">Cuando los videos no son comprables, la atencion se pierde.</h2><p className="mt-4 text-muted-foreground">Los videos comprables conectan demostraciones, UGC y contenido social con productos reales y siguientes pasos de compra.</p></div><div className="grid gap-3 sm:grid-cols-2">{problems.map((problem) => (<div key={problem} className="rounded-[8px] border border-border bg-surface p-4 text-sm text-muted-foreground">{problem}</div>))}</div></Container></Section>
      <Section spacing="lg" className="bg-surface"><Container><div className="max-w-3xl"><h2 className="text-3xl font-black tracking-normal">Funciones principales</h2><p className="mt-4 text-muted-foreground">Capacidades para convertir contenido visual en experiencias de producto mas accionables.</p></div><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, featureTitle, body]) => (<article key={featureTitle} className="rounded-[8px] border border-border bg-background p-6"><Icon aria-hidden="true" className="size-6 text-primary" /><h3 className="mt-4 text-xl font-black tracking-normal">{featureTitle}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p></article>))}</div></Container></Section>
      <Section id="pricing" spacing="lg"><Container><div className="max-w-3xl"><h2 className="text-3xl font-black tracking-normal">Planes segun biblioteca de video y trafico</h2><p className="mt-4 text-muted-foreground">Planes verificados contra Shopify App Store el {hyperAppsUpdatedAt}. Shopify es la fuente final de facturacion.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-4">{app.plans.map((plan) => (<article key={plan.name} className="flex min-h-[30rem] flex-col rounded-[8px] border border-border bg-surface p-5"><h3 className="text-xl font-black tracking-normal">{plan.name}</h3><p className="mt-3 text-3xl font-black tracking-normal">{plan.price}</p>{plan.trial ? <p className="mt-3 text-sm font-semibold text-primary">{plan.trial}</p> : null}<p className="mt-4 text-sm leading-6 text-muted-foreground">{plan.description}</p><ul className="mt-5 space-y-2">{plan.limits.slice(0, 5).map((item) => (<li key={item} className="flex gap-2 text-sm leading-5 text-muted-foreground"><CheckCircle2 aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-primary" /><span>{item}</span></li>))}</ul><Link href={app.installHref} className="mt-auto inline-flex min-h-11 items-center justify-center gap-2 rounded-[6px] bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90">{plan.cta ?? "Instalar"}</Link></article>))}</div></Container></Section>
      <Section spacing="lg" className="bg-surface"><Container size="md"><header className="text-center"><h2 className="text-3xl font-black tracking-normal">Preguntas frecuentes</h2></header><div className="mt-8 divide-y divide-border rounded-[8px] border border-border bg-background">{faq.map(([question, answer]) => (<details key={question} className="group p-5"><summary className="cursor-pointer list-none text-base font-black text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&::-webkit-details-marker]:hidden"><span className="flex items-center justify-between gap-4">{question}<span aria-hidden="true" className="text-primary">+</span></span></summary><p className="mt-4 text-sm leading-7 text-muted-foreground">{answer}</p></details>))}</div></Container></Section>
    </>
  );
}
