import Link from "next/link";
import { ArrowRight, BadgeCheck, BookOpenText, Clock3, FileText, ListChecks, Scale, Sparkles } from "lucide-react";

import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { formatToolDate, getAllTools } from "@/lib/tools";
import { createSpanishPageMetadata } from "@/lib/i18n/metadata";
import { publicImageSrc } from "@/lib/public-image-src";

export const dynamic = "force-dynamic";

export const metadata = createSpanishPageMetadata({
  title: "Herramientas ecommerce Shopify de Hyper Apps",
  description:
    "Usa herramientas de Hyper Apps para evaluar busqueda Shopify, descubrimiento, soporte, merchandising y prioridades de conversion.",
  path: "/es/tools",
});

const workflows = [["Auditar mas rapido", "Detecta brechas de busqueda, descubrimiento y conversion sin agregar procesos pesados.", BadgeCheck], ["Priorizar trabajo", "Convierte observaciones en pasos mas claros para merchandising, soporte y CX.", ListChecks], ["Compartir decisiones", "Usa salidas practicas para revisiones internas y planificacion.", FileText]] as const;
const relatedLinks = [["/es/blog", "Leer el blog", "Perspectivas practicas sobre descubrimiento y comercio IA.", BookOpenText], ["/es/comparisons", "Ver comparaciones", "Evalua soluciones Shopify con criterios mas claros.", Scale]] as const;

export default async function SpanishToolsPage() {
  const tools = await getAllTools();
  return (
    <>
      <Section spacing="none" className="pb-6 pt-10 sm:pb-8 sm:pt-14 lg:pt-16"><Container className="max-w-6xl"><div className="relative overflow-hidden rounded-3xl border border-border bg-surface px-6 py-7 shadow-[0_28px_70px_-46px_hsl(var(--shadow)/0.72)] sm:px-10 sm:py-9"><div className="relative grid gap-6 lg:grid-cols-[minmax(0,1fr)_16rem] lg:items-end"><div><div className="inline-flex items-center gap-2 rounded-full border border-border bg-background/80 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground"><Sparkles aria-hidden="true" className="size-3.5 text-primary" />Utilidades practicas</div><p className="mt-4 text-sm font-semibold uppercase tracking-[0.22em] text-primary">Herramientas Shopify de Hyper Apps</p><h1 className="mt-3 max-w-4xl type-display">Herramientas utiles para mejores decisiones ecommerce Shopify.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">Accede a utilidades enfocadas para auditorias de busqueda, revisiones de descubrimiento, planificacion de soporte, priorizacion de merchandising y trabajo de conversion tienda.</p></div><aside className="rounded-2xl border border-border bg-background/75 p-5 backdrop-blur sm:p-6"><FileText aria-hidden="true" className="size-5 text-primary" /><p className="mt-4 text-4xl font-semibold tracking-tight">{tools.length}</p><p className="mt-1 text-sm font-semibold text-foreground">{tools.length === 1 ? "herramienta publicada" : "herramientas publicadas"}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Para equipos Shopify que necesitan inspeccionar, priorizar y actuar.</p></aside></div></div></Container></Section>
      <Section spacing="none" className="pb-6 sm:pb-8"><Container className="max-w-6xl"><div className="grid gap-4 md:grid-cols-3">{workflows.map(([title, description, Icon]) => (<article key={title} className="rounded-2xl border border-border bg-surface p-5 shadow-sm"><span className="inline-flex size-10 items-center justify-center rounded-xl border border-border bg-background text-primary"><Icon aria-hidden="true" className="size-5" /></span><h2 className="mt-4 text-lg font-semibold tracking-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></article>))}</div></Container></Section>
      <Section spacing="none" className="pb-8 sm:pb-10"><Container className="max-w-6xl"><div className="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Biblioteca de herramientas</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Elige la utilidad Shopify que encaja con la tarea.</h2></div><p className="max-w-xl text-sm leading-6 text-muted-foreground sm:text-right">Explora utilidades practicas para auditar, priorizar y mejorar experiencias Shopify.</p></div>{tools.length ? <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{tools.map((tool) => { const displayDate = tool.updatedAt ?? tool.publishedAt; return <Link key={tool.slug} href={`/tools/${tool.slug}`} className="group flex h-full flex-col rounded-2xl border border-border bg-surface p-6 shadow-sm transition-all hover:-translate-y-1 hover:border-primary/45">{tool.coverImage ? <div className="-mx-6 -mt-6 mb-6 overflow-hidden border-b border-border bg-muted"><img src={publicImageSrc(tool.coverImage)} alt={tool.title} className="aspect-[16/9] w-full object-cover transition duration-300 group-hover:scale-[1.03]" loading="lazy" /></div> : null}<div className="flex items-start justify-between gap-4"><span className="inline-flex size-11 items-center justify-center rounded-xl border border-border bg-muted/60 text-primary"><FileText aria-hidden="true" className="size-5" /></span><span className="rounded-full border border-border bg-background px-3 py-1.5 text-xs font-semibold text-primary">{tool.toolType}</span></div><h3 className="mt-6 text-2xl font-semibold tracking-tight transition-colors group-hover:text-primary">{tool.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{tool.useCase || tool.excerpt}</p><div className="mt-auto flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-center sm:justify-between"><span className="inline-flex items-center gap-2 text-sm text-muted-foreground"><Clock3 aria-hidden="true" className="size-4" />{tool.readingTime} min de lectura</span><time dateTime={displayDate} className="text-sm font-medium text-muted-foreground">{formatToolDate(displayDate)}</time></div><span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-foreground transition-colors group-hover:text-primary">Abrir herramienta<ArrowRight aria-hidden="true" className="size-4" /></span></Link>; })}</div> : <div className="mt-6 grid place-items-center rounded-2xl border border-dashed border-border bg-surface px-6 py-12 text-center"><FileText aria-hidden="true" className="size-8 text-primary" /><h3 className="mt-4 text-2xl font-semibold tracking-tight">Las herramientas se estan preparando.</h3><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Auditorias, calculadoras, checklists y utilidades apareceran pronto.</p></div>}</Container></Section>
      <Section spacing="none" className="pb-12 sm:pb-16"><Container className="max-w-6xl"><div className="rounded-3xl border border-border bg-surface p-5 shadow-sm sm:p-6"><div className="mt-1 grid gap-4 md:grid-cols-2">{relatedLinks.map(([href, label, description, Icon]) => (<Link key={href} href={href} className="group rounded-2xl border border-border bg-background p-5 transition-all hover:-translate-y-0.5 hover:border-primary/40"><span className="inline-flex size-10 items-center justify-center rounded-xl border border-border bg-surface text-primary"><Icon aria-hidden="true" className="size-5" /></span><h3 className="mt-4 text-lg font-semibold tracking-tight transition-colors group-hover:text-primary">{label}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></Link>))}</div></div></Container></Section>
    </>
  );
}
